micronaut:
  application:
    name: book
  server:
    port: 8081

datasources:
  default:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_TCP_5432}/micronaut
    username: micronaut
    password: micronaut
    driverClassName: org.postgresql.Driver

jpa:
  default:
    packages-to-scan:
      - 'com.ekino.micronaut.book.domain'

flyway:
  locations: classpath:/db/migration, classpath:/db/data

eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
