micronaut:
  application:
    name: user
  server:
    port: 8082

datasources:
  default:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_TCP_5432}/micronaut
    username: micronaut
    password: micronaut
    driverClassName: org.postgresql.Driver

jpa:
  default:
    packages-to-scan:
      - 'com.ekino.micronaut.user.domain'

flyway:
  locations: classpath:/db/migration, classpath:/db/data

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

tracing:
  jaeger:
    enabled: true
    sender:
      agentHost: localhost
      agentPort: 5775
    sampler:
      probability: 1
