version: '3'

services:
  postgresql:
    restart: always
    image: postgres:10.4
    environment:
      - POSTGRES_DB=micronaut
      - POSTGRES_USER=micronaut
      - POSTGRES_PASSWORD=micronaut
    ports:
      - 5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U micronaut && sleep 2
      interval: 2s
      timeout: 5s
      retries: 10
